<a href="https://colab.research.google.com/github/itsyogi01/PYTHON--45DAYS-PRACTICE/blob/main/day09_numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [82]:
from numpy._core.fromnumeric import squeeze
movie = pd.read_csv("/content/bollywood.csv",usecols=[1]).squeeze("columns")
subs = pd.read_csv("/content/subs.csv",usecols=[0]).squeeze("columns")
VK = pd.read_csv("/content/kohli_ipl.csv")
vk = pd.read_csv("/content/kohli_ipl.csv",usecols=[1]).squeeze("columns")

In [6]:
# some important Series method
# astype
import sys
sys.getsizeof(vk)

1884

In [7]:
vk.astype('int16')
sys.getsizeof(vk.astype('int16'))

594

In [15]:
VK

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [27]:
# between
print(vk[vk.between(51,99)])
vk[vk.between(51,99)].size

33     58
40     71
43     56
44     67
51     70
56     57
67     73
70     51
72     58
73     65
79     57
80     93
81     99
84     56
96     67
98     73
102    51
103    62
109    82
115    75
116    79
118    80
121    52
126    75
128    54
130    54
131    62
133    64
136    55
140    58
143    57
144    92
147    68
151    70
159    84
161    67
174    72
177    90
187    72
196    51
197    53
208    58
212    73
Name: runs, dtype: int64

43

In [29]:
# clip
print(subs)
subs.clip(100,200)

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

0      100
1      100
2      100
3      100
4      100
      ...
360    200
361    200
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [30]:
# drop duplicate
temp = pd.Series([1,1,1,1,2,3,8,5,6])
temp

0    1
1    1
2    1
3    1
4    2
5    3
6    8
7    5
8    6
dtype: int64

In [31]:
temp.drop_duplicates()

0    1
4    2
5    3
6    8
7    5
8    6
dtype: int64

In [32]:
temp.drop_duplicates(keep = 'last')

3    1
4    2
5    3
6    8
7    5
8    6
dtype: int64

In [38]:
movie.size

1500

In [37]:
movie.drop_duplicates().size

1497

In [41]:
temp.duplicated().sum()

np.int64(3)

In [49]:
vk.duplicated().sum()

np.int64(137)

In [61]:
temp = pd.Series([1,2,3,4,5,6,np.nan,8,np.nan,10])
temp

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [53]:
print(temp.size)
print(temp.count())

10
8

In [55]:
vk.isnull().sum()

np.int64(0)

In [57]:
temp.isnull().sum()

np.int64(2)

In [62]:
# dropna
temp.dropna()
temp

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [68]:
# fillna
print(temp.fillna(0))
temp
temp.fillna(temp.mean())

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     0.0
7     8.0
8     0.0
9    10.0
dtype: float64

0     1.000
1     2.000
2     3.000
3     4.000
4     5.000
5     6.000
6     4.875
7     8.000
8     4.875
9    10.000
dtype: float64

In [72]:
# isin
(vk == 49) | (vk ==99)
vk[(vk == 49) | (vk ==99)]

81    99
85    49
Name: runs, dtype: int64

In [75]:
vk[vk.isin([49,99])]

81    99
85    49
Name: runs, dtype: int64

In [83]:

# apply
movie

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...
1495      Shah Rukh Khan
1496    Amitabh Bachchan
1497        Vivek Oberoi
1498          Ajay Devgn
1499        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [88]:
movie.apply(lambda x:x.split()[0].upper())

0         VICKY
1         VICKY
2        ANUPAM
3        EMRAAN
4          MONA
         ...
1495       SHAH
1496    AMITABH
1497      VIVEK
1498       AJAY
1499     AKSHAY
Name: lead, Length: 1500, dtype: object

In [91]:
subs.mean()
subs.apply(lambda x:"good day" if x>subs.mean() else "bad day")

0       bad day
1       bad day
2       bad day
3       bad day
4       bad day
         ...
360    good day
361    good day
362    good day
363    good day
364    good day
Name: Subscribers gained, Length: 365, dtype: object

In [121]:
from types import new_class
# copy
new= vk.head()
new

0    100
1     23
2     13
3     12
4      1
Name: runs, dtype: int64

In [120]:
new[0] = 100

new

0    100
1     23
2     13
3     12
4      1
Name: runs, dtype: int64

In [122]:
vk

0      100
1       23
2       13
3       12
4        1
      ...
210      0
211     20
212     73
213     25
214      7
Name: runs, Length: 215, dtype: int64

In [127]:
new=vk.head().copy()
new

0    100
1     23
2     13
3     12
4      1
Name: runs, dtype: int64

In [126]:
new[0] = 1
new

0     1
1    23
2    13
3    12
4     1
Name: runs, dtype: int64

In [128]:
vk

0      100
1       23
2       13
3       12
4        1
      ...
210      0
211     20
212     73
213     25
214      7
Name: runs, Length: 215, dtype: int64